// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivuibzedbnbndoyfpfrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2dWliemVkYm5ibmRveWZwZnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTE5MzYsImV4cCI6MjA2MDkyNzkzNn0.HX5foW5qkx-fSvBqHRrSNS1WhVFR1cqQ-euUV1X23WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);